### ISSUE TITLE
This is not buildable. Missing the Vulkan and Vulkan.Windows dlls. Where are these from?

### ISSUE THREAD

**Issue by rglaspey** [AdoriaSoftware/Infinivox#1]

**Comment by Masterchef365** [comment]
This really isn't a full project yet. Infinivox in it's current state isn't really ready for use outside of development yet. Sorry.

**Comment by rglaspey** [comment]
Well I can see that. Are the vulkan and vulkan.windows libraries yours or one of the vulkan ports here on github?

**Comment by Jimmacle** [comment]
The Vulkan assembly used in the repo can be built from the VulkanSharp project on GitHub: https://github.com/mono/VulkanSharp

I'm excited to see that people are coming across this project even though it's practically useless right now :P

**Comment by rglaspey** [comment]
Just so happens it touches a lot of areas I am interested in (vulkan, c#, voxel worlds, entity component systems). Thanks for the info.

**Comment by Jimmacle** [comment]
Well, we'd love to have more people help contribute if you're interested. We have a Discord (text/voice communicaton software) server here that we use to chat about development: https://discord.gg/0kDWLLcDXI7c5cvt
